export const environment = {
  production: true,
  googleMapsApiKey: 'YOUR_PRODUCTION_GOOGLE_MAPS_API_KEY',
  firebase: {
    apiKey: 'YOUR_PRODUCTION_FIREBASE_API_KEY',
    authDomain: 'YOUR_PRODUCTION_FIREBASE_AUTH_DOMAIN',
    databaseURL: 'YOUR_PRODUCTION_FIREBASE_DATABASE_URL',
    projectId: 'YOUR_PRODUCTION_FIREBASE_PROJECT_ID',
    storageBucket: 'YOUR_PRODUCTION_FIREBASE_STORAGE_BUCKET',
    messagingSenderId: 'YOUR_PRODUCTION_FIREBASE_MESSAGING_SENDER_ID',
    appId: 'YOUR_PRODUCTION_FIREBASE_APP_ID',
    measurementId: 'YOUR_PRODUCTION_FIREBASE_MEASUREMENT_ID'
  }
};